#language: node_js
#node_js:
#  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker tag udagram-api-user sudkul/udagram-api-user:v1
  - docker build -t udagram-frontend:local ./project/udagram-frontend
  - docker tag udagram-frontend:local sudkul/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker tag udagram-reverseproxy sudkul/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-feed:v1
  - docker push sudkul/udagram-api-user:v1
  - docker push sudkul/udagram-frontend:v1
  - docker push sudkul/udagram-reverseproxy:v1